import { Add } from '@/features/task/components/organisms/add';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Home() {
  return (
    <>
     <Add />
    </>
  );
}
